apiVersion: v1
kind: ConfigMap
metadata:
  name: school-config
  namespace: school
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  CSRF_TRUSTED_ORIGINS: "http://localhost,http://school.local"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
