apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: storage-class-patch.yaml
    target:
      kind: StatefulSet
      name: postgres

images:
  - name: ghcr.io/gabrielmcryu/school-management-devops
    newTag: "2500f787ca9baf3614b1b0f7a46deb36f84c01db"
